const express = require('express');
const fs = require('fs');
const path = require('path');
const os = require('os');
const cors = require('cors');

const app = express();
const PORT = 5000;

// Use same shared data path as gege-admin
const sharedDataPath = path.join(os.homedir(), 'AppData', 'Roaming', 'CaseFlowShared');
const accessKeysFile = path.join(sharedDataPath, 'access-keys.json');
const projectsFile = path.join(sharedDataPath, 'projects.json'); // Shared projects file
const localAccessKeysFile = path.join(sharedDataPath, 'accessKeys.json');

// Ensure shared directory exists
if (!fs.existsSync(sharedDataPath)) {
  fs.mkdirSync(sharedDataPath, { recursive: true });
}

// Initialize projects file if it doesn't exist
if (!fs.existsSync(projectsFile)) {
  fs.writeFileSync(projectsFile, JSON.stringify({}));
}

app.use(cors());
app.use(express.json({ limit: '50mb' }));

// Middleware to validate access key
const validateAccessKey = (req, res, next) => {
  const { company, accessKey } = req.body;
  
  if (!company || !accessKey) {
    return res.status(400).json({ error: 'Company name and access key are required' });
  }

  try {
    let accessKeysData = [];
    let keysSource = 'none';

    // Try to read from shared access keys file first (generated by gege-admin)
    if (fs.existsSync(accessKeysFile)) {
      try {
        const content = fs.readFileSync(accessKeysFile, 'utf-8').trim();
        if (content) {
          accessKeysData = JSON.parse(content);
          keysSource = 'shared';
        }
      } catch (e) {
        console.error('Error parsing shared access keys:', e);
      }
    }

    // Fallback: check local access keys file
    if (accessKeysData.length === 0 && fs.existsSync(localAccessKeysFile)) {
      try {
        const content = fs.readFileSync(localAccessKeysFile, 'utf-8').trim();
        if (content) {
          const localKeys = JSON.parse(content);
          if (Array.isArray(localKeys) && localKeys.length > 0) {
            accessKeysData = localKeys;
            keysSource = 'local';
          }
        }
      } catch (e) {
        console.error('Error parsing local access keys:', e);
      }
    }

    if (accessKeysData.length === 0) {
      console.warn(`No access keys found. Check: ${accessKeysFile} or ${localAccessKeysFile}`);
      return res.status(401).json({ error: 'No access keys configured. Generate a key in gege-admin first.' });
    }

    // Find the matching key in the access keys list
    const validKey = accessKeysData.find(k => 
      k.companyName === company && k.accessKey === accessKey.toUpperCase()
    );

    if (!validKey) {
      return res.status(401).json({ error: 'Invalid company name or access key' });
    }

    req.company = company;
    next();
  } catch (error) {
    console.error('Error validating access key:', error);
    res.status(500).json({ error: 'Authentication failed' });
  }
};

// Authenticate user (verify company + access key)
app.post('/api/auth/login', validateAccessKey, (req, res) => {
  try {
    const { company, accessKey } = req.body;
    
    // Return success with company info
    res.json({
      success: true,
      user: { 
        id: company, 
        company: company,
        accessKey: accessKey 
      }
    });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ error: 'Login failed' });
  }
});

// Get projects for a company
app.post('/api/projects/get', validateAccessKey, (req, res) => {
  try {
    const data = JSON.parse(fs.readFileSync(projectsFile, 'utf-8'));
    const company = req.company;
    res.json({ projects: data[company] || [] });
  } catch (error) {
    console.error('Error reading projects:', error);
    res.status(500).json({ error: 'Failed to read projects' });
  }
});

// Save projects for a company
app.post('/api/projects/save', validateAccessKey, (req, res) => {
  try {
    const data = JSON.parse(fs.readFileSync(projectsFile, 'utf-8'));
    const company = req.company;
    data[company] = req.body.projects;
    fs.writeFileSync(projectsFile, JSON.stringify(data, null, 2));
    res.json({ success: true });
  } catch (error) {
    console.error('Error saving projects:', error);
    res.status(500).json({ error: 'Failed to save projects' });
  }
});

// Health check
app.get('/api/health', (req, res) => {
  res.json({ status: 'online' });
});

app.listen(PORT, '0.0.0.0', () => {
  const interfaces = os.networkInterfaces();
  let ipAddress = 'localhost';
  
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        ipAddress = iface.address;
        break;
      }
    }
  }
  
  console.log(`ProjectFlow Server running on http://${ipAddress}:${PORT}`);
  console.log(`Local access: http://localhost:${PORT}`);
  console.log(`Access keys locations:`);
  console.log(`  - Shared (gege-admin): ${accessKeysFile}`);
  console.log(`  - Local fallback: ${localAccessKeysFile}`);
});
